<script setup>
import{onMounted,ref}from'vue';import PageShell from'../components/PageShell.vue';import MovieCard from'../components/MovieCard.vue';import StatusPanel from'../components/StatusPanel.vue';import{useMovieStore}from'../stores/movie';import{getRecommendations}from'../api/movie'
const store=useMovieStore(),movies=ref([]),loading=ref(true),error=ref(''),isFallback=ref(false);
function localRecommendations(){
  const favoriteIds=new Set(store.favorites.map(m=>Number(m.movieid))),preferred=new Set(store.favorites.flatMap(m=>String(m.typelist||'').split(/[,|/]/).map(x=>x.trim()).filter(Boolean)))
  return [...store.movies].filter(m=>!favoriteIds.has(Number(m.movieid))).map(m=>({...m,_score:m.averating+String(m.typelist||'').split(/[,|/]/).filter(t=>preferred.has(t.trim())).length*1.5})).sort((a,b)=>b._score-a._score||b.numrating-a.numrating).slice(0,10)
}
async function load(){loading.value=true;error.value='';isFallback.value=false;try{await store.loadMovies(true);const recs=await getRecommendations(store.user.userid);if(recs.length){movies.value=recs.map(r=>{const full=store.movies.find(m=>Number(m.movieid)===Number(r.movieid));return{...full,...r,picture:r.picture||full?.picture||'',description:r.description==='暂无剧情简介'?full?.description:r.description}})}else{movies.value=localRecommendations();isFallback.value=true}}catch(e){if(store.movies.length){movies.value=localRecommendations();isFallback.value=true}else error.value=e.message}finally{loading.value=false}}onMounted(load)
</script>
<template><PageShell><section class="recommend-hero"><div><span class="eyebrow">JUST FOR YOU</span><h1>猜你喜欢</h1><p>基于你的历史评分与协同过滤模型，为你精选更合口味的电影。</p></div><div class="ai-badge"><span>✦</span><b>AI 智能推荐</b><small>持续学习你的偏好</small></div></section><section class="content-section"><div class="section-heading"><div><h2>专属推荐片单</h2><p>{{isFallback?'离线计算结果生成前，已根据你的收藏类型与电影评分智能推荐':'推荐结果已按预测喜爱评分从高到低排列'}}</p></div><button class="secondary-button" :disabled="loading" @click="load">↻ 刷新推荐</button></div><div v-if="loading" class="movie-grid"><div v-for="n in 5" :key="n" class="skeleton"></div></div><StatusPanel v-else-if="error" icon="!" title="推荐加载失败" :text="error" action="重新加载" @action="load"/><StatusPanel v-else-if="!movies.length" icon="✦" title="暂时没有推荐结果" text="先收藏或评分几部电影，系统就能更懂你的喜好"/><div v-else class="movie-grid"><MovieCard v-for="(movie,i) in movies" :key="movie.movieid" :movie="movie" :index="i"/></div></section></PageShell></template>
