<script setup>
import{reactive,watch}from'vue';import{useRouter}from'vue-router';import PageShell from'../components/PageShell.vue';import{useMovieStore}from'../stores/movie'
const store=useMovieStore(),router=useRouter(),defaults={motion:true,heroEffects:true,notifications:true};
let saved={};try{saved=JSON.parse(localStorage.getItem('movie-preferences'))||{}}catch{}
const preferences=reactive({...defaults,...saved});
function apply(){document.documentElement.classList.toggle('reduce-effects',!preferences.motion);document.documentElement.classList.toggle('static-hero',!preferences.heroEffects)}
watch(preferences,()=>{localStorage.setItem('movie-preferences',JSON.stringify(preferences));apply()},{deep:true,immediate:true})
function clearFavorites(){if(confirm('确定清空全部收藏吗？'))store.clearFavorites()}
function resetPreferences(){Object.assign(preferences,defaults)}
function logout(){store.logout();router.push('/login')}
</script>
<template><PageShell><section class="settings-hero"><div class="settings-avatar">{{store.user?.username?.slice(0,1)?.toUpperCase()}}</div><div><span class="eyebrow">ACCOUNT SETTINGS</span><h1>用户设置</h1><p>管理个人资料、界面偏好与本地数据</p></div></section><section class="settings-layout"><aside class="settings-nav"><a href="#profile">个人资料</a><a href="#appearance">界面与体验</a><a href="#data">数据与账户</a></aside><div class="settings-content"><section id="profile" class="settings-card"><div class="settings-title"><span>◎</span><div><h2>个人资料</h2><p>当前登录账户信息</p></div></div><div class="profile-fields"><label>用户名<input :value="store.user?.username" disabled></label><label>用户编号<input :value="store.user?.userid" disabled></label></div><div class="settings-tip">账户资料由电影推荐系统后端统一管理。</div></section><section id="appearance" class="settings-card"><div class="settings-title"><span>✦</span><div><h2>界面与体验</h2><p>调整页面显示和交互效果</p></div></div><div class="setting-row"><div><b>页面动效</b><p>启用卡片渐入、悬浮和页面切换动画</p></div><label class="switch"><input v-model="preferences.motion" type="checkbox"><span></span></label></div><div class="setting-row"><div><b>首页视觉效果</b><p>启用首页电影背景的过渡和缩放效果</p></div><label class="switch"><input v-model="preferences.heroEffects" type="checkbox"><span></span></label></div><div class="setting-row"><div><b>消息提醒</b><p>显示评分成功、收藏变化等操作提示</p></div><label class="switch"><input v-model="preferences.notifications" type="checkbox"><span></span></label></div><button class="secondary-button" @click="resetPreferences">恢复默认设置</button></section><section id="data" class="settings-card"><div class="settings-title"><span>◇</span><div><h2>数据与账户</h2><p>管理保存在当前浏览器中的数据</p></div></div><div class="data-summary"><div><b>{{store.favorites.length}}</b><span>收藏电影</span></div><div><b>本机</b><span>数据存储位置</span></div></div><div class="account-actions"><button class="danger-button" :disabled="!store.favorites.length" @click="clearFavorites">清空收藏数据</button><button class="danger-button solid" @click="logout">退出当前账号</button></div></section></div></section></PageShell></template>
